services:
  gateway:
    build: .
    ports:
      - "5060:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  sql-server:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:80"
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Survey_Api2022
  rabbitmq:
    image: rabbitmq
    ports:
        - 5672:80
        - 15672:80
  redis:
    image: redis
    ports:
      - '6379:80'
  survey-api:
    build: ./../SurveyMe.SurveysApi/
    ports:
      - "5067:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  person-api:
    build: ./../SurveyMe.PersonApi/
    ports:
      - "5050:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  mongo:
    image: mongo
    ports:
      - "27017:80"