services:
  gateway:
    build: .
    ports:
      - "5060:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  survey-api-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1430:1430"
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Survey_Api2022

  rabbitmq:
    image: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672

  survey-api-cache:
    image: redis
    ports:
      - '6379:6379'

  survey-api:
    build: ./../SurveyMe.SurveysApi/
    ports:
      - "5067:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  person-api:
    build: ./../SurveyMe.PersonApi/
    ports:
      - "5050:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  person-api-db:
    image: mongo
    ports:
      - "27017:80"

  statistics-api-db:
    image: postgres
    environment:
      POSTGRES_DB: "StatisticsDb"
      POSTGRES_USER: "StatisticsApi"
      POSTGRES_PASSWORD: "StatisticsApi_2022"
    ports:
      - "5432:5432"

  statistics-api:
    build: ./../SurveyMe.StatisticsApi/
    ports:
      - "5077:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  answers-api:
    build: ./../SurveyMe.AnswersApi/
    ports:
      - "5007:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  answers-api-cache:
      image: redis
       
      ports:
        - '6370:6370'

  answers-api-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1431:1431"
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Answers_Api2022

  authentication-api:
    build: ./../SurveyMe.AuthenticationApi/
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  authentication-api-db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Authentication_Api2022